[default]
address = "127.0.0.1"
port = 8000

[default.databases.bibimbap]
url = "postgres://postgres:password@127.0.0.1:5432/bibimbap"
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
database_name = "bibimbap"
